server:
  port: 9094

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shipmentDB
    username: postgres
    password: dream1234
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: postgresql
